### ISSUE TITLE
Integrate CException into sensor libraries

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/elastic-ai.runtime.enV5#102]
## Concept

Integrate the CException library into the sensor libraries to get rid of the returned error codes and improve use for enduser.

## ToDo

- [x] SHT3x
- [x] #277
- [x] #309
- [x] BMI323

**Comment by DavidFederl** [comment]
Integrationg CException into the BMI323 library is not possible. If we want to use this library with CException we have to implement a facade first!

**Comment by LeoBuron** [comment]
See #309.
