### ISSUE TITLE
Check if Interrupt handling with FreeRTOS can be improved

### ISSUE THREAD

**Issue by DerDavidos** [es-ude/elastic-ai.runtime.enV5#127]

**Comment by DerDavidos** [comment]
An iImplementation for a own FreeRTOS task for the interrupt is finished, but it is not clear yet if this improves the handling.

**Comment by HerrCooker** [comment]
- STOP command with no effect, if sending while device is publishing

**Comment by DerDavidos** [comment]
done with other issues
