### ISSUE TITLE
Get bytes per page from Device/Twin

### ISSUE THREAD

**Issue by DerDavidos** [es-ude/elastic-ai.runtime.enV5#140]
The value in question dedicated how many bytes the device downloads at one from the server. The Flash bytes per page value defined int src/flash/include/Flash.h should to be accessible to the Server providing the bitfile to avoid having to adjust it manually for changes or different devices. This could be done within the Status message of the Device/Twin. Maybe the twin stores this information or the twin gets it from the device.

**Comment by DavidFederl** [comment]
Additionally we should publish the number of pages per sector. Because this is relevant for to determine the correct start address.

---

Otherwise we can leave this calculation to the enV5 and instead of sending an address we only send the sector where the write should start.
