### ISSUE TITLE
Check Error when Downloading to Flash via HTTP

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/elastic-ai.runtime.enV5#147]
When files are downloaded to the flash via HttpGet some Bits are flipped, when read out via the FPGA.
If we read out the flash via the Python script on the other hand all Bytes are correct!

**Comment by glencoe** [comment]
@HerrCooker As you've done #149 , can you comment on this issue?

@DavidFederl, @HerrCooker  I suggest we either check the python script the same way as in #149 or officially call it broken.

**Comment by HerrCooker** [comment]
@DavidFederl and I have checked the readback from Vivado after flashing via HTTP, using several different files. All of the readbacks had no difference, when compared to the source files.

**Comment by DavidFederl** [comment]
@glencoe: I would suggest to simply test the USB flash script to verify if it's working correctly. Because this should only take about 15 minutes. If it doesn't work correctly than we should flag it as broken and don't fix it for now.

**Comment by HerrCooker** [comment]
@glencoe I flashed the fast blinking .bin file and the echo_server .bin file via USB and checked the readback files against the source files. Both times there were no differences.
