### ISSUE TITLE
Read Flash via FPGA

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/elastic-ai.runtime.enV5#149]
Read out the Flash of enV5 via the FPGA.

Required for #147 !!

---

**ToDo's**
- [x] Research on possible ways to accomplish read out via Vivado
- [x] Read out the flash after flashing the echo_server file

**Comment by DavidFederl** [comment]
A Vivado installation should be provided on PC 3 inside the Lab.

**Comment by DavidFederl** [comment]
Startpoint: https://docs.xilinx.com/api/khub/documents/kvUq08rrVXVKQR2Vrtl3UQ/content?Ft-Calling-App=ft%2Fturnkey-portal&Ft-Calling-App-Version=4.2.15#G8.364401

**Comment by DavidFederl** [comment]
Have you added a manual on how to accomlish this? If so feel free to close this issue and #147.

**Comment by HerrCooker** [comment]
@DavidFederl The manual is almost finished. When I'm done with it, where should it be published?

**Comment by DavidFederl** [comment]
> @DavidFederl The manual is almost finished. When I'm done with it, where should it be published?

I guess the ’bitfile_scripts’ folder inside the enV5 repo would be a good place.
