### ISSUE TITLE
Wrist.c in src folder

### ISSUE THREAD

**Issue by telefonjoker100** [es-ude/elastic-ai.runtime.enV5#167]
Hey,
I'm not sure, if it is the right channel for submitting such things. So let me know if I should submit information like this to you differently. 

Why is the wrist.c file inside our src folder? Shouldn't it be inside of the ball-challenge repository?

**Comment by DerDavidos** [comment]
Yes, it was removed form the src folder and can now be found as the Main in the BallChallange repo
