### ISSUE TITLE
Can the env5 enter boot_loader mode byitself

### ISSUE THREAD

**Issue by telefonjoker100** [es-ude/elastic-ai.runtime.enV5#168]
Can the env5 enter the boot_loader automatically with a command? 
If so, how would I do this?

**Comment by DerDavidos** [comment]
You can register this FreeRTOS task to be able to send 'r' via UART to trigger a reboot. Or alternatively include the if anywhere in you code.

```c
_Noreturn void enterBootModeTask(void) {
    while (true) {
        if (getchar_timeout_us(10) == 'r' || !stdio_usb_connected()) {
            reset_usb_boot(0, 0);
        }
    }
}
```
