### ISSUE TITLE
Add Init script

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/elastic-ai.runtime.enV5#169]
Add an initialization script to 
- [ ] check required toolchains (maybe install if not found)
- [ ] install and configure husky, commitlint
- [ ]  pull git submodules
- [ ] setup IDE configs if required

**Comment by glencoe** [comment]
see also https://github.com/es-ude/elastic-ai.runtime.enV5/pull/165#discussion_r1393788350

**Comment by DavidFederl** [comment]
Moved to Backlog in favor of #170 

---

Script has to provide support for:
- [ ] MacOSX
- [ ] Linux
- [ ] Windows
