### ISSUE TITLE
Genrate Dependency Graph from CMake

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/elastic-ai.runtime.enV5#172]
Retrieve information about tools to generate a dependency graph from the CMake Configuration Files.

**Comment by DavidFederl** [comment]
Info: [CMake GraphViz Option](https://cmake.org/cmake/help/latest/module/CMakeGraphVizOptions.html)

---

```bash
# IMPORTANT: otherwise project root directory flooded with temp files
mdkir depGraph && cd depGraph

# generate dot files
cmake -S .. -graphviz=enV5.dot

# convert to png file
dot -T png -o enV5.<target>.png enV5.dot.<target>
```

**Comment by DavidFederl** [comment]
Add graph generation as target to CMake!!

**Comment by DerDavidos** [comment]
With the given graphviz options it was not possible to generate a dependency graph without the enormous dependencies inside the external libraries. However, a workaround with multiple regex replacements is functioning.
