### ISSUE TITLE
Make PRINT Macros act like c statements

### ISSUE THREAD

**Issue by glencoe** [es-ude/elastic-ai.runtime.enV5#186]
Use the print and debug macros as shown in our c lecture.

**Comment by DavidFederl** [comment]
Implement PRINT like
```C
#define PRINT(str,...) \
    do {  \
        ... \
    } while (false)
```
-> requires `;` after macro call

---

Use if to distinguish if debug should be executed
-> compiler sees code => prevends unexpected behaviour
-> compiler will remove statments on optimization
