### ISSUE TITLE
Fix Memory Leak in HTTP module

### ISSUE THREAD

**Issue by glencoe** [es-ude/elastic-ai.runtime.enV5#188]
Throwing the exception without freeing `httpGet` creates a memory leak.

https://github.com/es-ude/elastic-ai.runtime.enV5/blob/36bfab0102bf26f8a9d53af830812be35a0a2658/src/network/http/HTTP.c#L33

Is there a reason why we're using malloc here instead of the stack?

**Comment by DavidFederl** [comment]
## Solution

Remove malloc calls for url! Instead use dynamic sized char array like `char url[length];`
=> will be automatically cleaned on function leave (regular & CException)
