### ISSUE TITLE
add time interface

### ISSUE THREAD

**Issue by PandiasChild** [es-ude/elastic-ai.runtime.enV5#285]
add a time interface which provides a facade for the pico-sdk Time

- [x] add get_current_time_in_us
- [x] add get_current_time_in_ms
- [x] add dummie for unittests

**Comment by DavidFederl** [comment]
> 
> @DavidFederl 
> I had to name the interface "timeFacade" since using "time" was a duplicated name and coursed an error. we should think about merging "sleep_interface" and "time_facade_interface" and finding a suiting name for it. they are both facades of the same library.
> 
> 
> 

Why not `time_interface` for the CMake library and `Time.h` for the header. They are case sensitive.
