### ISSUE TITLE
fix pico SDK deps

### ISSUE THREAD

**Issue by glencoe** [es-ude/elastic-ai.runtime.enV5#319]
## The Problem
Even though there are facades to pico functionalities, direct pico sdk dependencies leak to many other places in the project. This makes it difficult to reason about dependencies, breakages, write unit tests, etc.
The `hal` module should act as a barrier between pico sdk and the rest of our code base. As such, no other module is supposed to directly include pico. One reason for the problems is a mix of inversing dependencies to pico via linkage during build time and via injection during runtime. Let's have a look at the Uart module here:

The Uart module should prevent me from having to mess with the pico sdk, however to use Uart I need several things:

 - Uart.c/Uart.h
 - EnV5HwConfiguration.h
 - Pico::hardware_uart
 - Pico::hardware_irq
 - Pico::pico_runtime
 - Gpio
 - Common

Even though there is a forward declaration of `uart_inst_t` in `Uart.h`, we force users to create a `uart_inst_t` data structure.
The `EnV5HwConfiguration.h` contains symbol for that data structure. But that definition looks like this

```c
#define UART_MODULE UART_INSTANCE(1)
```

The macro `UART_INSTANCE()` is not defined in that header. In fact nothing in the configuration header specifies where `UART_INSTANCE` is defined. But since we actually want to define a struct from the pico sdk, we need to depend on it and use it to initialize that `uart_inst_t` field in a struct that will be passed to `Uart_init` for initialization.

Now we have pico dependencies on many levels, we have a pico build dependency for the uart module and our executable (or every other module that needs to specify the uart instance).

As we cannot avoid the build time dependency on the pico sdk the hal layer should serve as a complete barrier against all things pico. That means, no symbol, no function, no data type, no macro is supposed to escape that barrier. As soon as something that is not `hal` needs to directly depend on pico sdk we have violated that rule.

## The Fix

If we really need to offer different Uart devices our `Uart.h` should specify the options. E.g.,

```c
enum {UART_DEVICE_ONE = 0, UART_DEVICE_TWO = 1};
```

and `EnV5HwConfiguration.h` should now depend on `Uart.h` instead of the other way around e.g.,

```c
#include "Uart.h"

#define UART_DEVICE UART_DEVICE_ONE
```

In fact only the executable file should depend on `EnV5HwConfiguration.h`. Even more, instead of preprocessor symbols that header file could contain static initialized structs already. Assuming we need a `UartConfig` struct we could just write

```c
#include "Uart.h"

static UartConfig default_uart_config = {.device = UART_DEVICE_ONE};
```
and in `main.c`

```c
#include "EnV5HwConfiguration.h"

int main(void) {
  Uart_init(&default_uart_config);
  Uart_write("my data", 7);
}
```

So the envisioned structure should look like this

```mermaid

classDiagram
  UartPico --> PicoSdk
  GpioPico --> PicoSdk
  UartPico --|> UartHdr
  GpioPico --|> GpioHdr
  EnV5HwConfiguration --> UartHdr
  EnV5HwConfiguration --> GpioHdr

```

**Comment by LeoBuron** [comment]
Not planned as single issue. But should be done as sum of the boyscout rule
